ci: coverage tests benchmarks

coverage:
	go test -cover ./certificates/...
	go test -cover ./fs/...
	go test -cover ./tlsp/...

tests:
	go test -v ./certificates/...
	go test -v ./fs/...
	go test -v ./tlsp/...

benchmarks:
	go test -run=xXX -bench=. ./certificates/...
	go test -run=xXX -bench=. ./fs/...
	go test -run=xXX -bench=. ./tlsp/...

