ci: coverage tests benchmarks

coverage:
	go test -cover ./certificates/...
	go test -cover ./fs/...
	go test -cover ./tlsp/...
	go test -cover

tests:
	go test -v ./certificates/...
	go test -v ./fs/...
	go test -v ./tlsp/...
	go test -v

benchmarks:
	go test -run=xXX -bench=. ./certificates/...
	go test -run=xXX -bench=. ./fs/...
	go test -run=xXX -bench=. ./tlsp/...
	go test -run=xXX -bench=.

